# -*- coding: utf-8 -*-
"""RiditasFirstFileTesting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JSEgEuGRt8N2Qqg3UWNKb8W1cArtmlTW
"""

print("Hello world")